[package]
name = "serde-wasm-bindgen"
version = "0.1.0"
authors = ["Ingvar Stepanyan <me@rreverser.com>"]
edition = "2018"

[dependencies]
serde = "^1.0"
js-sys = "^0.3"
wasm-bindgen = "^0.2.43"
fnv = "1.0.6"

[dev-dependencies]
wasm-bindgen-test = "0.2.39"
serde = { version = "^1.0", features = ["derive"] }
serde_bytes = "0.10.5"
serde_json = "1.0.39"

[workspace]
members = ["benchmarks"]

[profile.release]
lto = true
codegen-units = 1

[patch.crates-io.wasm-bindgen]
git = "https://github.com/rustwasm/wasm-bindgen"

[patch.crates-io.js-sys]
git = "https://github.com/rustwasm/wasm-bindgen"
