[package]
name = "serde-wasm-bindgen"
version = "0.1.0"
authors = ["Ingvar Stepanyan <me@rreverser.com>"]
edition = "2018"

[dependencies]
serde = "^1.0"
js-sys = "^0.3"
wasm-bindgen = "^0.2"

[dev-dependencies]
wasm-bindgen-test = "0.2.39"
serde = { version = "^1.0", features = ["derive"] }
serde_bytes = "0.10.5"
serde_json = "1.0.39"
